sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1
  - ARCH_TRAVIS_CONFIRM_YES=1

language: c

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - openssh
    # aur
    - neofetch
  script:
    - "sudo neofetch"
    
script:
  - "bash ./.arch-travis.sh"
  - "sudo sh update_motd.sh"